import = ["~/.config/alacritty/color-schemes.toml", "~/.config/alacritty/fonts.toml"]

shell = "bash"

[window]
  title = "alacritty"
  decorations = "None"
  opacity = 0.968
  padding = { x = 6, y = 6 }

