return {
  "williamboman/mason-lspconfig.nvim",
  opts = {
    ensure_installed = {
      "astro",
      "autotools_ls", 
      "bashls",
      "clangd",
      "cssls",
      "dhall_lsp_server",
      "dockerls",
      "elixirls",
      "eslint", 
      "fsautocomplete",
      "golangci_lint_ls",
      "gopls",
      "html",
      "julials",
      "marksman",
      "purescriptls",
      "pyright",
      "reason_ls",
      "ruff",
      "rust_analyzer",
      "solidity_ls",
      "sqls",
      "svelte",
      "terraformls",
      "ts_ls",
      "tsp_server",
      "volar@1.8.27",
      "yamlls",
      "zls", 
    },
  },
}
