return {
  "williamboman/mason-lspconfig.nvim",
  opts = {
    ensure_installed = {
      "astro",
      "autotools_ls", 
      "bashls",
      "clangd",
      "cssls",
      "dockerls",
      "eslint", 
      "golangci_lint_ls",
      "gopls",
      "html",
      "julials",
      "marksman",
      "pyright",
      "rnix",
      "ruff_lsp",
      "rust_analyzer",
      "solc",
      "terraformls",
      "tsserver",
      "volar@1.8.27",
      "unocss",
      "zls", 
    },
  },
}
