return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  opts = {
    ensure_installed = {
      "astro-language-server",
      "autotools-language-server", 
      "bash-language-server",
      "clangd",
      "css-lsp",
      "dhall-lsp",
      "docker-language-server",
      "elixir-ls",
      "eslint-lsp", 
      "fsautocomplete",
      "golangci-lint",
      "gopls",
      "html-lsp",
      "hyprls",
      "julia-lsp",
      "marksman",
      "purescript-language-server",
      "pyright",
      "reason-language-server",
      "ruff-lsp",
      "rust-analyzer",
      "solidity-ls",
      "svelte-language-server",
      "terraform-ls",
      "typescript-language-server",
      -- "tsp_server",
      -- "volar@1.8.27",
      "vue-language-server",
      "yaml-language-server",
      "zls", 
    },
  },
}
