return {
  "AstroNvim/astrocore",
  ---@type AstroCoreOpts
  opts = {
    -- Configuration of treesitter features in Neovim
    treesitter = {
      highlight = true,
      indent = true,
      ensure_installed = {
        "astro",
        "bash",
        "c",
        "css",
        "csv",
        "cue",
        "dhall",
        "dockerfile",
        "elixir",
        "fish",
        "fsharp",
        "go",
        "hcl",
        "html",
        "json",
        "kdl",
        "latex",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "meson",
        "nickel",
        "ninja",
        "nix",
        "ocaml",
        "pony",
        "python",
        "purescript",
        "roc",
        "rust",
        "scala",
        "scss",
        "solidity",
        "ssh_config",
        "svelte",
        "terraform",
        "todotxt",
        "toml",
        "typescript",
        "typespec",
        "vhdl",
        "vue",
        "yaml",
        "zig",
      },
    },
  },
}
