#!/usr/bin/env bash

src="${BASH_SOURCE[0]}"
curr_dir="$(dirname "$src")"
dot_dir="$(dirname "$curr_dir")"
export DOTFILES="$dot_dir"

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

source "$DOTFILES/bash/paths.sh"
source "$DOTFILES/bash/helpers/platform.sh"

[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# custom bash prompt
source "$DOTFILES/bash/command-prompt.sh"

# add support for kitty helpers
source "$DOTFILES/kitty/select.sh"

# add additional commands
source "$DOTFILES/bash/extension.sh"

# darwin specific
if [[ "$(platform::is_darwin)" == "1" ]]; then 
  source "$DOTFILES/bash/extension.darwin.sh"
  source "$DOTFILES/darwin/git-completion.bash"
  export FONTCONFIG_FILE=/usr/local/etc/fonts/fonts.conf
  nix_profile_comp="$HOME/.nix-profile/etc/profile.d/bash_completion.sh"
  [ -s "$nix_profile_comp" ] && source "$nix_profile_comp"
fi

# add aliases
source "$DOTFILES/bash/aliases.sh"

# add mc completion
complete -C /personal-files/bin/mc mc


macchina
