#!/usr/bin/env bash

src="${BASH_SOURCE[0]}"
curr_dir="$(dirname "$src")"
dot_dir="$(dirname "$curr_dir")"
export DOTFILES="$dot_dir"

source_if_exists() {
  local fpath="$1"
  if test -s "$fpath"; then
    source "$fpath"
  fi
}

# load paths
source "$DOTFILES/bash/paths.sh"

# custom bash prompt
source "$DOTFILES/bash/command-prompt.sh"

# add support for kitty helpers
source "$DOTFILES/kitty/select.sh"

# add additional commands
source "$DOTFILES/bash/extension.sh"

# add aliases
source "$DOTFILES/bash/aliases.sh"

# add mc completion
complete -C "$(which mc)" mc

# load platform helpers
source "$DOTFILES/bash/helpers/platform.sh"

# darwin specific
if platform::is_darwin; then
  source "$DOTFILES/bash/extension.darwin.sh"
  source "$DOTFILES/darwin/git-completion.bash"
  export FONTCONFIG_FILE=/usr/local/etc/fonts/fonts.conf
  nix_profile_comp="$HOME/.nix-profile/etc/profile.d/bash_completion.sh"
  source_if_exists "$nix_profile_comp"
fi

# load additional programs
source_if_exists "$NVM_DIR/nvm.sh"
source_if_exists "$NVM_DIR/bash_completion"
source_if_exists "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"

macchina
