#!/usr/bin/env bash

# set dotfiles path
export DOTFILES=/personal-files/dotfiles

# modify PS1
source $DOTFILES/bash/command-prompt.sh

# set gopath and goroot
export GOPATH="/personal-files/gopath"
export GOENV="$GOPATH/env"
export GOROOT="/personal-files/go"

# set zigpath
export ZIGPATH="/personal-files/zig"

# add custom binaries and golang to path
export PERSONAL_BIN="/personal-files/bin"
export PATH="$PERSONAL_BIN:$GOROOT/bin:$GOPATH/bin:$ZIGPATH:$PATH"
export WIREGUARD_TUNNEL_NAME="tunnel"

# add podman user-level service/socket as docker host
export DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock

## DDO launcher. Added this because steam was struggling to launch DDO.
ddo-launch() {
  local pfx=$(realpath ~/.steam/debian-installation/steamapps/compatdata/206480/pfx)
  local rootdir="$(realpath ~/.steam/debian-installation/steamapps/common/Dungeons\ and\ Dragons\ Online)"

  echo "prefix: $pfx"
  echo "rootdir: $rootdir"
  echo ""
  env WINEPREFIX=$pfx wine "$rootdir/DNDLauncher.exe"
}


source $DOTFILES/bash/rustrc
source $DOTFILES/bash/tunnel.sh
source $DOTFILES/bash/hidden.sh # TODO: need a better way to inject/import this.

reload-bash() {
  source ~/.bashrc
}

# call neofetch
#neofetch
macchina
